### PR TITLE
Redux_Options_text refactoring to support new HTML5 input types and attrs

### PR DESCRIPTION
**Pull request by tivnet**

### CODE REVIEW

**Comment by tivnet** [comment]
@ghost1227 : any comments? Thank you!

**Comment by evertiro** [comment]
I want to perform some more testing before committing this due to the amount of modification it requires to what is one of the most commonly used field types. However, I wholeheartedly agree that we need to support HTML5 input types (and probably non-input elements too).

**Comment by evertiro** [comment]
I've included this in the 3.0.0 milestone

**Comment by tivnet** [comment]
@ghost1227 
In that case, please do not keep it is a workaround, but make the proper 'type'  => 'number' (email, tel, etc), without the additional parameter I invented.

**Comment by evertiro** [comment]
We've got at least partial HTML5 support in the 3.0.0 release, and we'll keep on improving it!

**Comment by dovy** [comment]
Closed and request moved to new repo for further evaluation.

**Pull request closed without merging**
