### PR TITLE
New fields and parameters

### PR DESCRIPTION
**Pull request by psaikali**
- Added 'color_states', 'text_sortable', 'slider', 'gfonts', 'bg_bundle' fields. 
  /\* - Added 'direction' parameter to 'color_gradient' (Horizontal / Vertical). > ignore this one, validation on color field screws the direction param, needs to be added as a new field */
- Added 'number' parameter to 'text' field.
- Added 'next_to_hide' parameter to 'checkbox_hide_below' to set how many (next) fields you want to hide.
- Added 'switch' parameter to 'checkbox_hide_below' so it looks like a switch, like the other checkboxes.
- Added 'multiple' parameter to 'post_type_select' to be able to choose more than 1 post type.
- Added 'safe_fonts' parameter to 'gfonts' field.
## Color states:

screen-2013-01-08-4 54 09 PM
## Text sortable:

screen-2013-01-08-4 36 28 PM
## Slider:

screen-2013-01-08-7 15 45 PM
## Gfonts:

screen-2013-01-08-4 43 01 PM
## Background bundle:

screen-2013-01-08-11 23 02 PM
## Color gradient with 'direction' => true: (to be ignored, validation screws the direction value storing)

screen-2013-01-08-4 45 21 PM
## Text with 'number' => true:

screen-2013-01-08-4 42 40 PM
## post_type_select with 'multiple' => true:

screen-2013-01-08-9 46 37 PM
## gfonts field with 'safe_fonts' => true:

screen-2013-01-09-1 03 59 PM

### CODE REVIEW

**Comment by psaikali** [comment]
The 'color_gradient' direction is not saved because of the validation on it, I spent an hour finding this :( Too tired to edit it right now, just letting you know. Might be better to create a new field type OR do some magic (magic that I can't do, my skills are limited) around:

```
                        if($field['type'] == 'color' || $field['type'] == 'color_gradient') {
                            //$field['validate'] = 'color';
                        }
```

**Comment by evertiro** [comment]
Ok... sorting through all of this and so far I have the following questions...
1. What is the custom.css modification for and why put it there instead of default.css?
2. You seem to have missed the bg_bundle.js file.

**Comment by psaikali** [comment]
Great!
1. My bad, I initially wrote these fields/css without thinking about sending them to you, that's why I put my css in custom.css for later updates.
2. I actually haven't finished the bg_bundle.js logic, so I removed it but forget to dis-enqueue the js. Sorry 'bout that. I wanted to disable the dropdowns (position / repetition) if no image was uploaded, but couldn't find a working JS event for "an image has been defined/removed in this field".

My apologies is this pull-request is a bit of a mess, I'm quite new to GitHub interactions ;) Let me know if you have further questions.

**Comment by psaikali** [comment]
BTW the custom.css includes styling for:
- gfonts field (chozen library)
- text sortable field
- slider field (jQuery Simple Slider plugin)

**Comment by evertiro** [comment]
On second thought... can you resubmit the pull request with a request for each field type?

**Comment by psaikali** [comment]
Sure, I'll try to do that later today!

2013/1/14 Ghost1227 notifications@github.com

> On second thought... can you resubmit the pull request with a request for
> each field type?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ghost1227/Redux-Framework/pull/42#issuecomment-12234362.

## 

Pierre Saïkali
psaikali@gmail.com

**Comment by evertiro** [comment]
Closing until separate pull requests are posted.

**Pull request closed without merging**
